import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { BookOpen, Target, Trash2, Clock, Sparkles, BookMarked, Bot, PenLine } from "lucide-react";
import { ContentItem } from "@/interfaces/content";
import QuestionAssignmentDialog from "./QuestionAssignmentDialog";
import { formatDistanceToNow } from "date-fns";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";

interface QuestionBankTableProps {
  questions: ContentItem[];
  onRefresh?: () => void;
  onDelete?: (id: string) => void;
}

const QuestionBankTable = ({ questions, onRefresh, onDelete }: QuestionBankTableProps) => {
  const getDifficultyColor = (difficulty?: string) => {
    const d = difficulty?.toLowerCase()?.trim();
    switch (d) {
      case "easy": return "bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-400";
      case "medium": return "bg-yellow-100 text-yellow-800 dark:bg-yellow-900/30 dark:text-yellow-400";
      case "hard": return "bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-400";
      case "mix":
      case "mixed":
        return "bg-purple-100 text-purple-800 dark:bg-purple-900/30 dark:text-purple-400";
      default: 
        return "bg-purple-100 text-purple-800 dark:bg-purple-900/30 dark:text-purple-400";
    }
  };
  
  const getDifficultyLabel = (difficulty?: string) => {
    const d = difficulty?.toLowerCase()?.trim();
    if (d === 'easy' || d === 'medium' || d === 'hard') {
      return difficulty;
    }
    return 'Mix';
  };

  const getSourceInfo = (sourceType?: string | null) => {
    const source = sourceType?.toLowerCase();
    if (source === 'rag_generated' || source === 'rag') {
      return {
        icon: BookMarked,
        label: 'From Book',
        color: 'bg-emerald-100 text-emerald-800 dark:bg-emerald-900/30 dark:text-emerald-400',
        tooltip: 'Generated from uploaded course material using RAG'
      };
    }
    if (source === 'ai_generated' || source === 'auto_fill') {
      return {
        icon: Bot,
        label: 'AI Generated',
        color: 'bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-400',
        tooltip: 'Generated by AI (Gemini) based on topic context'
      };
    }
    return {
      icon: PenLine,
      label: 'Manual',
      color: 'bg-slate-100 text-slate-700 dark:bg-slate-800/50 dark:text-slate-300',
      tooltip: 'Manually added by admin or uploaded via CSV'
    };
  };

  const getRelativeTime = (dateString?: string) => {
    if (!dateString) return null;
    try {
      const date = new Date(dateString);
      const distance = formatDistanceToNow(date, { addSuffix: true });
      const diffMs = Date.now() - date.getTime();
      const isJustNow = diffMs < 5 * 60 * 1000;
      return { text: isJustNow ? "Just now" : distance, isRecent: diffMs < 60 * 60 * 1000 };
    } catch {
      return null;
    }
  };

  return (
    <TooltipProvider>
      <div className="border rounded-lg overflow-hidden">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead className="min-w-[280px]">Question</TableHead>
              <TableHead>Subject / Topic</TableHead>
              <TableHead>Difficulty</TableHead>
              <TableHead>Source</TableHead>
              <TableHead>Added</TableHead>
              <TableHead className="text-right">Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {questions.length === 0 ? (
              <TableRow>
                <TableCell colSpan={6} className="text-center py-8 text-muted-foreground">
                  No questions found
                </TableCell>
              </TableRow>
            ) : (
              questions.map((question) => {
                const timeInfo = getRelativeTime(question.createdAt);
                const sourceInfo = getSourceInfo((question as any).source_type || question.sourceType);
                const SourceIcon = sourceInfo.icon;
                return (
                  <TableRow key={question.id}>
                    <TableCell className="max-w-md">
                      <div className="space-y-1">
                        <div className="font-medium line-clamp-2">{question.title}</div>
                        {question.description && (
                          <div className="text-sm text-muted-foreground line-clamp-1">
                            {question.description}
                          </div>
                        )}
                      </div>
                    </TableCell>
                    <TableCell>
                      <div className="flex flex-col gap-1">
                        {question.subject && (
                          <Badge variant="outline" className="flex items-center gap-1 w-fit text-xs">
                            <BookOpen className="w-3 h-3" />
                            {question.subject}
                          </Badge>
                        )}
                        {question.topic && (
                          <Badge variant="secondary" className="flex items-center gap-1 w-fit text-xs">
                            <Target className="w-3 h-3" />
                            {question.topic}
                          </Badge>
                        )}
                      </div>
                    </TableCell>
                    <TableCell>
                      <Badge className={getDifficultyColor(question.difficulty)}>
                        {getDifficultyLabel(question.difficulty)}
                      </Badge>
                    </TableCell>
                    <TableCell>
                      <Tooltip>
                        <TooltipTrigger asChild>
                          <Badge className={`${sourceInfo.color} flex items-center gap-1 cursor-help`}>
                            <SourceIcon className="w-3 h-3" />
                            {sourceInfo.label}
                          </Badge>
                        </TooltipTrigger>
                        <TooltipContent>
                          <p className="text-xs">{sourceInfo.tooltip}</p>
                        </TooltipContent>
                      </Tooltip>
                    </TableCell>
                    <TableCell>
                      {timeInfo && (
                        <div className="flex items-center gap-1.5">
                          {timeInfo.isRecent ? (
                            <Sparkles className="w-3.5 h-3.5 text-amber-500" />
                          ) : (
                            <Clock className="w-3.5 h-3.5 text-muted-foreground" />
                          )}
                          <span className={`text-sm ${timeInfo.isRecent ? "text-amber-600 dark:text-amber-400 font-medium" : "text-muted-foreground"}`}>
                            {timeInfo.text}
                          </span>
                        </div>
                      )}
                    </TableCell>
                  <TableCell className="text-right">
                    <div className="flex items-center justify-end gap-1">
                      <QuestionAssignmentDialog
                        questionId={question.id}
                        questionTitle={question.title}
                        currentSubject={question.subject}
                        currentTopic={question.topic}
                        onAssignmentComplete={onRefresh}
                      />
                      {onDelete && (
                        <Button
                          size="sm"
                          variant="ghost"
                          onClick={() => onDelete(question.id)}
                        >
                          <Trash2 className="h-4 w-4" />
                        </Button>
                      )}
                    </div>
                  </TableCell>
                </TableRow>
              );
            })
            )}
          </TableBody>
        </Table>
      </div>
    </TooltipProvider>
  );
};

export default QuestionBankTable;
