// LAZY page registry — used by the browser App.tsx.
//
// Same keys as src/routes/eagerPages.tsx, but every page is a separate chunk so
// none of them land in the entry bundle that every visitor parses before paint.
// Prerendered HTML still ships full body content because src/prerender.tsx uses
// the eager registry instead.
import { lazyWithReload } from "./lazyWithReload";
import type { PageMap } from "./pageMap";

export const pages: PageMap = {
  Index: lazyWithReload(() => import("@/pages/Index")),
  NotFound: lazyWithReload(() => import("@/pages/NotFound")),
  DeleteAccount: lazyWithReload(() => import("@/pages/DeleteAccount")),
  AICoachLanding: lazyWithReload(() => import("@/pages/AICoachLanding")),
  Subjects: lazyWithReload(() => import("@/pages/Subjects")),
  MockTests: lazyWithReload(() => import("@/pages/MockTests")),
  Leaderboard: lazyWithReload(() => import("@/pages/Leaderboard")),
  PastPapers: lazyWithReload(() => import("@/pages/PastPapers")),
  Jobs: lazyWithReload(() => import("@/pages/Jobs")),
  Scholarships: lazyWithReload(() => import("@/pages/Scholarships")),
  CustomSyllabus: lazyWithReload(() => import("@/pages/CustomSyllabus")),
  Reviews: lazyWithReload(() => import("@/pages/Reviews")),
  Quizzes: lazyWithReload(() => import("@/pages/Quizzes")),
  QuestionBank: lazyWithReload(() => import("@/pages/QuestionBank")),
  About: lazyWithReload(() => import("@/pages/About")),
  Contact: lazyWithReload(() => import("@/pages/Contact")),
  FAQ: lazyWithReload(() => import("@/pages/FAQ")),
  StudyGuides: lazyWithReload(() => import("@/pages/StudyGuides")),
  Blog: lazyWithReload(() => import("@/pages/Blog")),
  Announcements: lazyWithReload(() => import("@/pages/Announcements")),
  Boards: lazyWithReload(() => import("@/pages/Boards")),
  Tools: lazyWithReload(() => import("@/pages/Tools")),
  PrivacyPolicy: lazyWithReload(() => import("@/pages/legal/PrivacyPolicy")),
  TermsOfService: lazyWithReload(() => import("@/pages/legal/TermsOfService")),
  EditorialPolicy: lazyWithReload(() => import("@/pages/legal/EditorialPolicy")),
  ExamsHub: lazyWithReload(() => import("@/pages/exams/ExamsHub")),
  ExamLandingPage: lazyWithReload(() => import("@/pages/exams/ExamLandingPage")),
  NumsEntryTest: lazyWithReload(() => import("@/pages/exams/NumsEntryTest")),
  IbaSukkurEntryTest: lazyWithReload(() => import("@/pages/exams/IbaSukkurEntryTest")),
  LatLawAdmissionTest: lazyWithReload(() => import("@/pages/exams/LatLawAdmissionTest")),
  ProgrammaticIndex: lazyWithReload(() => import("@/pages/programmatic/ProgrammaticIndex")),
  ProgrammaticLandingPage: lazyWithReload(() => import("@/pages/programmatic/ProgrammaticLandingPage")),
  MDCATSyllabus: lazyWithReload(() => import("@/pages/MDCATSyllabus")),
  MDCATPastPapers: lazyWithReload(() => import("@/pages/seo/MDCATPastPapers")),
  PPSCPastPapers: lazyWithReload(() => import("@/pages/seo/PPSCPastPapers")),
  FPSCPastPapers: lazyWithReload(() => import("@/pages/seo/FPSCPastPapers")),
  CSSMCQs: lazyWithReload(() => import("@/pages/seo/CSSMCQs")),
  ECATPreparation: lazyWithReload(() => import("@/pages/seo/ECATPreparation")),
  NUSTEntryTest: lazyWithReload(() => import("@/pages/seo/NUSTEntryTest")),
  PunjabUniversityEntryTest: lazyWithReload(() => import("@/pages/seo/PunjabUniversityEntryTest")),
  COMSATSEntryTest: lazyWithReload(() => import("@/pages/seo/COMSATSEntryTest")),
  SindhUniversitiesEntryTest: lazyWithReload(() => import("@/pages/seo/SindhUniversitiesEntryTest")),
  EngineeringUniversitiesEntryTest: lazyWithReload(() => import("@/pages/seo/EngineeringUniversitiesEntryTest")),
  PSTSSTTestPreparation: lazyWithReload(() => import("@/pages/seo/PSTSSTTestPreparation")),
  NinthClassMCQs: lazyWithReload(() => import("@/pages/seo/NinthClassMCQs")),
  BoardMCQs: lazyWithReload(() => import("@/pages/seo/BoardMCQs")),
  PakArmyTest: lazyWithReload(() => import("@/pages/seo/PakArmyTest")),
  PAFTest: lazyWithReload(() => import("@/pages/seo/PAFTest")),
  ASFTest: lazyWithReload(() => import("@/pages/seo/ASFTest")),
  ForcesJobsTests: lazyWithReload(() => import("@/pages/seo/ForcesJobsTests")),
  AggregateCalculator: lazyWithReload(() => import("@/pages/tools/AggregateCalculator")),
  MeritCalculator: lazyWithReload(() => import("@/pages/tools/MeritCalculator")),
  GPACalculator: lazyWithReload(() => import("@/pages/tools/GPACalculator")),
  CGPACalculator: lazyWithReload(() => import("@/pages/tools/CGPACalculator")),
  GPAToPercentage: lazyWithReload(() => import("@/pages/tools/GPAToPercentage")),
  PercentageToGPA: lazyWithReload(() => import("@/pages/tools/PercentageToGPA")),
  MarksCalculator: lazyWithReload(() => import("@/pages/tools/MarksCalculator")),
  ResultCalculator: lazyWithReload(() => import("@/pages/tools/ResultCalculator")),
  AttendanceCalculator: lazyWithReload(() => import("@/pages/tools/AttendanceCalculator")),
  PercentageCalculator: lazyWithReload(() => import("@/pages/tools/PercentageCalculator")),
  PeriodicTable: lazyWithReload(() => import("@/pages/tools/PeriodicTable")),
  PakistanTaxCalculator: lazyWithReload(() => import("@/pages/tools/PakistanTaxCalculator")),
  ZakatCalculator: lazyWithReload(() => import("@/pages/tools/ZakatCalculator")),
  AttendanceDashboard: lazyWithReload(() => import("@/pages/tools/AttendanceDashboard")),
};

export default pages;
