import { useState, useRef, useEffect } from "react";
import { 
  Book, Code, Beaker, Brain, Atom, Calculator, Scale, Landmark, Globe, 
  Dumbbell, BarChart, DollarSign, Users, ShoppingCart, ScrollText, 
  FileCheck, Zap, Building, Wrench, Cpu, Stethoscope, Microscope, Plus
} from "lucide-react";
import { motion } from "framer-motion";
import Header from "@/components/Header";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { useNavigate, useLocation } from "react-router-dom";
import { toast } from "@/components/ui/use-toast";
import { useAuth } from "@/contexts/AuthContext";
import { supabase } from "@/integrations/supabase/client";

// Import subjects data
import { subjects } from "@/data/subjectsData";

// Import custom components
import { CustomSubject, QuizSettings } from "@/components/custom-syllabus/interfaces";
import EnhancedSubjectFilter from "@/components/custom-syllabus/EnhancedSubjectFilter";
import SubjectCard from "@/components/custom-syllabus/SubjectCard";
import QuizPanel from "@/components/custom-syllabus/QuizPanel";
import { generateTopicsForSubject, getCategories } from "@/components/custom-syllabus/utils";

const CustomSyllabus = () => {
  const [isLoaded, setIsLoaded] = useState(false);
  const [selectedCategory, setSelectedCategory] = useState<string>("All");
  const [searchQuery, setSearchQuery] = useState("");
  const [customSubjects, setCustomSubjects] = useState<CustomSubject[]>([]);
  const [syllabusName, setSyllabusName] = useState("My Custom Syllabus");
  const [selectedTopicsCount, setSelectedTopicsCount] = useState(0);
  const [selectedSubjectsCount, setSelectedSubjectsCount] = useState(0);
  const [activeTab, setActiveTab] = useState("topics");
  const [isGenerating, setIsGenerating] = useState(false);
  const [quizSettings, setQuizSettings] = useState<QuizSettings>({
    timeLimit: 30,
    questionsCount: 20,
    difficulty: "medium"
  });
  
  const navigate = useNavigate();
  const location = useLocation();
  const { user } = useAuth();
  const selectedTopicsRef = useRef<HTMLDivElement>(null);
  const hasAutoGenerated = useRef(false);
  
  // Check for pre-filled subject from navigation (e.g., from Dashboard weakness card)
  const locationState = location.state as { prefilledSubject?: string; autoGenerate?: boolean } | null;

  useEffect(() => {
    setIsLoaded(true);
    
    const prefilledSubject = locationState?.prefilledSubject;
    
    const initialCustomSubjects: CustomSubject[] = subjects.map(subject => {
      // Check if this subject should be pre-selected (case-insensitive match)
      const shouldPreselect = prefilledSubject && 
        subject.title.toLowerCase().includes(prefilledSubject.toLowerCase());
      
      return {
        ...subject,
        expanded: shouldPreselect || false,
        selected: shouldPreselect || false,
        topics: generateTopicsForSubject(subject.title, subject.topicCount).map(topic => ({
          ...topic,
          selected: shouldPreselect || false
        }))
      };
    });
    
    setCustomSubjects(initialCustomSubjects);
    
    // Update syllabus name if pre-filled
    if (prefilledSubject) {
      setSyllabusName(`${prefilledSubject} Practice Test`);
      
      // Show a toast to inform the user
      toast({
        title: "Subject Pre-selected",
        description: `${prefilledSubject} has been selected. Click "Create Quiz" to generate a practice test.`,
      });
    }
  }, [locationState?.prefilledSubject]);

  useEffect(() => {
    let topicsCount = 0;
    let subjectsCount = 0;
    
    customSubjects.forEach(subject => {
      const selectedTopicsInSubject = subject.topics.filter(topic => topic.selected).length;
      if (selectedTopicsInSubject > 0) {
        subjectsCount++;
        topicsCount += selectedTopicsInSubject;
      }
    });
    
    setSelectedTopicsCount(topicsCount);
    setSelectedSubjectsCount(subjectsCount);
  }, [customSubjects]);

  // Auto-generate quiz when navigating with autoGenerate flag
  useEffect(() => {
    if (
      locationState?.autoGenerate &&
      selectedTopicsCount > 0 &&
      !hasAutoGenerated.current &&
      !isGenerating
    ) {
      hasAutoGenerated.current = true;
      createQuiz();
    }
  }, [locationState?.autoGenerate, selectedTopicsCount, isGenerating]);

  const toggleSubjectSelection = (subjectTitle: string) => {
    setCustomSubjects(prev => prev.map(subject => {
      if (subject.title === subjectTitle) {
        const newSelectedState = !subject.selected;
        return {
          ...subject,
          selected: newSelectedState,
          topics: subject.topics.map(topic => ({
            ...topic,
            selected: newSelectedState
          }))
        };
      }
      return subject;
    }));
  };

  const toggleTopicSelection = (subjectTitle: string, topicId: string) => {
    setCustomSubjects(prev => prev.map(subject => {
      if (subject.title === subjectTitle) {
        return {
          ...subject,
          topics: subject.topics.map(topic => {
            if (topic.id === topicId) {
              return { ...topic, selected: !topic.selected };
            }
            return topic;
          }),
          selected: subject.selected || subject.topics.some(t => t.id === topicId && !t.selected)
        };
      }
      return subject;
    }));
  };

  const toggleSubjectExpansion = (subjectTitle: string) => {
    setCustomSubjects(prev => prev.map(subject => {
      if (subject.title === subjectTitle) {
        return { ...subject, expanded: !subject.expanded };
      }
      return subject;
    }));
  };

  const updateQuizSettings = (setting: keyof QuizSettings, value: any) => {
    setQuizSettings(prev => ({
      ...prev,
      [setting]: value
    }));
  };

  const createQuiz = async () => {
    // Login wall - allow browsing but require auth for generation
    if (!user) {
      toast({
        title: "Sign in to Continue",
        description: "Please sign in to generate personalized AI tests.",
      });
      navigate('/auth');
      return;
    }

    if (selectedTopicsCount === 0) {
      toast({
        title: "Selection Required",
        description: "Please select at least one topic for your custom quiz.",
        variant: "destructive"
      });
      return;
    }

    setIsGenerating(true);

    try {
      // Step A: Gather selected topics into a comma-separated string
      const selectedTopicsString = customSubjects
        .filter(subject => subject.topics.some(topic => topic.selected))
        .map(subject => {
          const topics = subject.topics.filter(topic => topic.selected).map(t => t.name).join(', ');
          return `${subject.title}: ${topics}`;
        })
        .join('; ');

      // Step B: Call AI to generate test
      const { data: aiResponse, error: aiError } = await supabase.functions.invoke('generate-test', {
        body: {
          topic: selectedTopicsString,
          difficulty: quizSettings.difficulty,
          question_count: quizSettings.questionsCount
        }
      });

      if (aiError) {
        console.error('AI generation error:', aiError);
        
        // Check if the error contains rate limit or payment required messages
        const errorMessage = aiError.message || '';
        
        if (errorMessage.includes('Rate limit') || errorMessage.includes('429')) {
          toast({
            title: "Too Many Requests",
            description: "You're generating quizzes too quickly. Please wait a moment and try again.",
            variant: "destructive"
          });
        } else if (errorMessage.includes('credits') || errorMessage.includes('402')) {
          toast({
            title: "Credits Depleted",
            description: "AI credits are depleted. Please add credits to your workspace in Settings.",
            variant: "destructive"
          });
        } else {
          toast({
            title: "Generation Failed",
            description: "Failed to generate quiz questions. Please try again.",
            variant: "destructive"
          });
        }
        return;
      }

      // Validate the AI response has the expected data
      if (!aiResponse || !aiResponse.questions || aiResponse.questions.length === 0) {
        toast({
          title: "Generation Failed",
          description: "AI generated an invalid response. Please try again.",
          variant: "destructive"
        });
        return;
      }

      // Step C: Save to database
      const { data: sessionData, error: dbError } = await supabase
        .from('custom_test_sessions')
        .insert({
          user_id: user.id,
          session_name: syllabusName,
          question_count: quizSettings.questionsCount,
          time_limit: quizSettings.timeLimit,
          difficulty_levels: [quizSettings.difficulty],
          questions: aiResponse.questions,
          subjects: customSubjects
            .filter(subject => subject.topics.some(topic => topic.selected))
            .map(subject => subject.title),
          topics: customSubjects
            .filter(subject => subject.topics.some(topic => topic.selected))
            .map(subject => ({
              subject: subject.title,
              topics: subject.topics.filter(topic => topic.selected).map(t => t.name)
            }))
        })
        .select()
        .single();

      if (dbError) {
        console.error('Database error:', dbError);
        toast({
          title: "Save Failed",
          description: "Failed to save your quiz. Please try again.",
          variant: "destructive"
        });
        return;
      }

      toast({
        title: "Quiz Created!",
        description: `Your AI-generated quiz "${syllabusName}" is ready with ${quizSettings.questionsCount} questions.`,
      });

      // Step D: Navigate to test session
      navigate(`/test-session/${sessionData.id}`);
    } catch (error) {
      console.error('Unexpected error:', error);
      toast({
        title: "Error",
        description: "An unexpected error occurred. Please try again.",
        variant: "destructive"
      });
    } finally {
      setIsGenerating(false);
    }
  };

  const scrollToSelectedTopics = () => {
    selectedTopicsRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  const filteredSubjects = customSubjects.filter(subject => {
    const categoryMatch = selectedCategory === "All" || subject.category === selectedCategory;
    const searchMatch = subject.title.toLowerCase().includes(searchQuery.toLowerCase()) || 
                       subject.topics.some(topic => topic.name.toLowerCase().includes(searchQuery.toLowerCase()));
    return categoryMatch && searchMatch;
  });

  const container = {
    hidden: { opacity: 0 },
    show: {
      opacity: 1,
      transition: {
        staggerChildren: 0.1,
      },
    },
  };

  const item = {
    hidden: { y: 20, opacity: 0 },
    show: { y: 0, opacity: 1 },
  };

  return (
    <Header>
      <div className="max-w-7xl mx-auto px-4 pt-6 pb-12">
        {/* Hero Header */}
        <motion.div
          className="mb-6 text-center"
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
        >
          <h1 className="text-3xl md:text-4xl font-bold mb-2 bg-gradient-to-r from-primary via-accent to-primary bg-clip-text text-transparent">
            Custom Syllabus Builder
          </h1>
          <p className="text-base text-muted-foreground max-w-2xl mx-auto mb-4">
            Select topics from various subjects to create your personalized test
          </p>
          <div className="flex items-center justify-center gap-3 flex-wrap">
            <Badge variant="secondary" className="px-3 py-1.5 text-sm">
              <span className="text-primary font-bold mr-1">{selectedSubjectsCount}</span> Subjects
            </Badge>
            <Badge variant="secondary" className="px-3 py-1.5 text-sm">
              <span className="text-primary font-bold mr-1">{selectedTopicsCount}</span> Topics
            </Badge>
          </div>
        </motion.div>
        
        {/* Main Content Grid */}
        <div className="grid grid-cols-1 gap-4 lg:grid-cols-3">
          {/* Left: Subjects Grid */}
          <div className="lg:col-span-2 space-y-4" ref={selectedTopicsRef}>
            <EnhancedSubjectFilter
              searchQuery={searchQuery}
              setSearchQuery={setSearchQuery}
              selectedCategory={selectedCategory}
              setSelectedCategory={setSelectedCategory}
              categories={getCategories(subjects)}
            />

            <motion.div
              variants={container}
              initial="hidden"
              animate={isLoaded ? "show" : "hidden"}
              className="grid grid-cols-1 sm:grid-cols-2 gap-3"
            >
              {filteredSubjects.length > 0 ? (
                filteredSubjects.map((subject) => (
                  <motion.div key={subject.title} variants={item}>
                    <SubjectCard
                      subject={subject}
                      toggleSubjectSelection={toggleSubjectSelection}
                      toggleTopicSelection={toggleTopicSelection}
                      toggleSubjectExpansion={toggleSubjectExpansion}
                    />
                  </motion.div>
                ))
              ) : (
                <div className="col-span-full">
                  <Card className="p-8 text-center">
                    <p className="text-muted-foreground mb-4">No subjects or topics match your search criteria.</p>
                    <Button onClick={() => {
                      setSearchQuery("");
                      setSelectedCategory("All");
                    }}>Clear Filters</Button>
                  </Card>
                </div>
              )}
            </motion.div>
          </div>
          
          {/* Right: Sticky Quiz Panel */}
          <div className="lg:col-span-1">
            <div className="sticky top-20">
              <QuizPanel
                syllabusName={syllabusName}
                setSyllabusName={setSyllabusName}
                selectedTopicsCount={selectedTopicsCount}
                selectedSubjectsCount={selectedSubjectsCount}
                activeTab={activeTab}
                setActiveTab={setActiveTab}
                quizSettings={quizSettings}
                updateQuizSettings={updateQuizSettings}
                createQuiz={createQuiz}
                customSubjects={customSubjects}
                setSelectedCategory={setSelectedCategory}
                isGenerating={isGenerating}
              />
            </div>
            
            {selectedTopicsCount > 0 && (
              <div className="fixed bottom-6 right-6 lg:hidden">
                <Button onClick={scrollToSelectedTopics} size="lg" className="shadow-lg">
                  Review Selection ({selectedTopicsCount})
                </Button>
              </div>
            )}
          </div>
        </div>
      </div>
    </Header>
  );
};

export default CustomSyllabus;
