
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzhvipkcssxrsxxljbbz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6aHZpcGtjc3N4cnN4eGxqYmJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMjAzODYsImV4cCI6MjA1OTU5NjM4Nn0.XILYqQfW-4sqxdLXIfklKHLJVHH_tY5Ci0xNk4Kxbyw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
